# Generated by Django 3.0.7 on 2020-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200905_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='police',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
